// src/locales/en.ts
export default {
  app: {
    title: 'T&C Simplifier',
    description: 'Simplify complex terms and conditions into easy-to-understand bullet points.',
  },
  home: {
    title: 'T&C Simplifier',
    subtitle: 'Tired of complicated legal jargon? Paste a URL to simplify terms and conditions into clear, concise bullet points.',
    error: {
      title: 'Simplification Error',
      aiNoSummary: 'The AI could not generate a summary. Please try a different URL or check the page content.',
      unexpected: 'An unexpected error occurred while simplifying the terms and conditions. Please try again.',
    },
    shareCurrentSummary: 'Share Current Summary',
    shareTextPrefix: "Here's a simplified summary of the T&C for {url}, generated by {appName}:",
    footerText: '© {year} T&C Simplifier. Understand better, faster.',
    helpAndSupport: 'Help & Support',
    developerContact: 'Developer Contact',
  },
  urlInputForm: {
    title: 'Enter Terms & Conditions URL',
    description: 'Paste the URL of a terms and conditions page and choose your preferred language for the summary.',
    urlLabel: 'URL',
    urlPlaceholder: 'https://example.com/terms',
    languageLabel: 'Summary Language',
    languagePlaceholder: 'Select language',
    buttonLoading: 'Simplifying...',
    buttonSimplify: 'Simplify Terms',
  },
  summaryDisplay: {
    title: 'Simplified Summary',
    noPoints: 'No summary points available.',
  },
  historySection: {
    title: 'Simplification History',
    clearAll: 'Clear All',
    description: 'Previously simplified terms and conditions.',
    empty: 'No history yet. Simplify some terms to see them here.',
    share: 'Share',
    delete: 'Delete',
  },
  toast: {
    storageError: {
      title: 'Storage Error',
      description: 'Could not save history. Your browser storage might be full or disabled.',
    },
    sharedSuccessfully: {
      title: 'Shared successfully!',
    },
    shareError: {
      title: 'Share Error',
      description: 'Could not share the summary.',
    },
    copiedToClipboard: {
      title: 'Copied to clipboard!',
      description: 'Summary and URL copied as Web Share is not available.',
    },
    copyError: {
      title: 'Copy Error',
      description: 'Could not copy summary to clipboard.',
    },
    historyItemDeleted: {
      title: 'History item deleted.',
    },
    allHistoryCleared: {
      title: 'All history cleared.',
    },
  },
  languageSwitcher: {
    selectPlaceholder: 'Select UI Language',
  },
  languages: {
    en: 'English',
    es: 'Español',
    fr: 'Français',
    hi: 'हिन्दी',
    bn: 'বাংলা',
    ta: 'தமிழ்',
    te: 'తెలుగు',
    mr: 'मराठी',
    gu: 'ગુજરાતી',
    kn: 'ಕನ್ನಡ',
    ml: 'മലയാളം',
    pa: 'ਪੰਜਾਬੀ',
    or: 'ଓଡ଼ିଆ',
  },
  helpDialog: {
    title: "Help & Support",
    q1Title: "How to use T&C Simplifier?",
    q1Answer1: "1. Paste the URL of the terms and conditions page you want to simplify into the input field.",
    q1Answer2: "2. Select your preferred language for the summary from the dropdown menu.",
    q1Answer3: "3. Click the 'Simplify Terms' button.",
    q1Answer4: "4. The simplified summary will appear below. You can then share it or find it later in your history.",
    q2Title: "Is my data saved?",
    q2Answer: "Your simplification history (URL, summary, timestamp) is saved locally in your browser's storage. It is not sent to any server. You can clear your history at any time.",
    q3Title: "What if I get an error?",
    q3Answer: "Ensure the URL is correct and publicly accessible. Some complex page structures or very long documents might occasionally cause issues. Try a different URL if problems persist.",
  },
  contactDialog: {
    title: "Developer Contact",
    intro: "For inquiries, feedback, or support, please reach out to:",
    email: "vinay.sharma03d@gmail.com",
    note: "Please note: This is a demo application.",
  },
  dialog: {
    close: "Close",
  }
} as const;
